//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimBuilding
    {
        public DimBuilding()
        {
            this.DimModules = new HashSet<DimModule>();
        }
    
        public int id { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> KeyFacility { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual DimFacility DimFacility { get; set; }
        public virtual ICollection<DimModule> DimModules { get; set; }
    }
}
