//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimCountry
    {
        public DimCountry()
        {
            this.DimFacilities = new HashSet<DimFacility>();
        }
    
        public int id { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> KeyRegion { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual ICollection<DimFacility> DimFacilities { get; set; }
        public virtual DimRegion DimRegion { get; set; }
    }
}
