//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FFCubeEntities : DbContext
    {
        public FFCubeEntities()
            : base("name=FFCubeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimBucket> DimBuckets { get; set; }
        public virtual DbSet<DimBuilding> DimBuildings { get; set; }
        public virtual DbSet<DimBusinessPartner> DimBusinessPartners { get; set; }
        public virtual DbSet<DimBusinessUnit> DimBusinessUnits { get; set; }
        public virtual DbSet<DimCostCenter> DimCostCenters { get; set; }
        public virtual DbSet<DimCountry> DimCountries { get; set; }
        public virtual DbSet<DimFacility> DimFacilities { get; set; }
        public virtual DbSet<DimFFInstance> DimFFInstances { get; set; }
        public virtual DbSet<DimFinancialCompany> DimFinancialCompanies { get; set; }
        public virtual DbSet<DimModule> DimModules { get; set; }
        public virtual DbSet<DimPhysicalStation> DimPhysicalStations { get; set; }
        public virtual DbSet<DimRegion> DimRegions { get; set; }
        public virtual DbSet<DimStationType> DimStationTypes { get; set; }
    }
}
